// import 'package:flutter/material.dart';
//
// void main() {
//   runApp(const FigmaToCodeApp());
// }
//
// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           Iphone1415ProMax2(),
//         ]),
//       ),
//     );
//   }
// }
//
// class Iphone1415ProMax2 extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 430,
//           height: 932,
//           clipBehavior: Clip.antiAlias,
//           decoration: BoxDecoration(color: Colors.white),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: -54,
//                 top: -21,
//                 child: Container(
//                   width: 537,
//                   height: 953,
//                   decoration: BoxDecoration(
//                     // image: DecorationImage(
//                     //   image: NetworkImage("https://via.placeholder.com/537x953"),
//                     //   fit: BoxFit.fill,
//                     // ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 430,
//                 top: 0,
//                 child: Transform(
//                   transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
//                   child: Container(width: 932, height: 430),
//                 ),
//               ),
//               Positioned(
//                 left: 141,
//                 top: 392,
//                 child: Container(
//                   width: 147,
//                   height: 147,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://via.placeholder.com/147x147"),
//                       fit: BoxFit.fill,
//                     ),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }